### ISSUE TITLE
Need to update to use jQuery instead of Prototype

### ISSUE THREAD

**Issue by srveit** [joshnuss/spree-faq#3]
I tried this extension, but when I go to the Question Categories Admin
panel and clieck New Category, I get the following Javascript error:

   Element.hide is not a function

It appears it is calling Prototype methods and Prototype is no longer loaded with Spree. I am using the default admin layout from Spree HEAD. Here are the libraries that are loaded:

<pre>
/store/javascripts/jquery.js
/store/javascripts/jquery-ui.js
/store/javascripts/jrails.js
/store/javascripts/jquery.suggest
/store/javascripts/jrails.autocomplete
/store/javascripts/jquery.template
/store/javascripts/spree.js
/store/javascripts/nested-attribute.js
/store/javascripts/zone.js
/store/javascripts/calculator.js
/store/javascripts/gateway.js
/store/javascripts/jquery.alerts/jquery.alerts.js
/store/javascripts/datepicker.js
/store/javascripts/lang/en.js
</pre>

plus the following Javascript:

<pre>
$ = jQuery;
var AUTH_TOKEN = "v6MpjL7TvtTlBmUKNA3JDLH+zNtnsU74JR2x1yWGQIA=";
jQuery.alerts.dialogClass = 'spree';
</pre>

**Comment by joshnuss** [comment]
Hi srveit,
Can you tell me what version of spree you are using? 
Thanks

**Comment by srveit** [comment]
I am using the HEAD. The lastest version that I am using is commit 28ecc60d3aaaab97d1f4c1a25028be6b48b4df91.

**Comment by joshnuss** [comment]
ok fixed. Thanks for letting me know. happy hacking

**Comment by shakti123** [comment]
Good, jquery is good then other functions. Thanks srveit for the version. I was took a suggestion from www.designingtips.com about this version. But i think you can give better.
